1.Импорт библиотеки NumPy с общепринятым сокращением.

In [2]:
#Импорт библиотеки NumPy с сокращением до np, для уменьшения объёма кода
import numpy as np

2. Примеры создания массивов:

In [7]:
#Создание массива из обычного списка
list_1 = [1, 2, 3, 4, 5] #Создаем список "a"
array = np.array(list_1) #Преобразовываем список в массив, посредством функции np.array()
print("Массив:", array)#Выводим массив

Массив: [1 2 3 4 5]


In [24]:
#Создание двумерного массива из вложенного списка
list_2 = [[1,2,3],[4,5,6]] #Создаём вложенный список
array_of_2d = np.array(list_2) #Преобразовываем вложенный список в двумерный массив
print("Двумерный массив:") #Выводим сообщение о том, что это двумерный массив
print(array_of_2d) #Выводим массив

Двумерный массив:
[[1 2 3]
 [4 5 6]]


In [ ]:
#Создание массива с помощью функции 'zeros'
zeros_array = np.zeros([5,3]) #С помощью функции 'np.zeros' создаем массив созданный из нулей
print("Выводим массив из нулей:", zeros_array) #Выводим массив из нулей

Выводим массив из нулей: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
#Создание массива с помощью функции 'ones'
ones_massive = np.ones([2,4]) #С помощью функции 'np.ones' создаем массив из единиц, имеющий размер 2х4
print("Выводим массив из единиц:")
print(ones_massive)

Выводим массив из единиц:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
#Создание массива с помощью функции 'arange'
r_array = np.arange(4, 12, 2) #С помощью функции 'arange' создаем массив от 4 до 12, с шагом 2
print("Выводим массив чисел от 4 до 12, с шагом 2:")
print(r_array)

Выводим массив чисел от 4 до 12, с шагом 2:
[ 4  6  8 10]


3. Демонстрация атрибутов:

In [ ]:
#Вывод формы двумерного массива
print("Форма массива:", array_of_2d.shape) #Выводим форму массива

Форма массива: (2, 3)


In [ ]:
#Вывод типа данных двумерного массива
print("Тип данных массива:", array_of_2d.dtype) #Выводим тип данных массива

Тип данных массива: int64


4. Примеры индексирования и срезов:

In [8]:
#Создаем массив для демонстрации индексирования и срезов
og_array = np.array([10, 20, 30, 40, 50, 60, 70, 80])
print("Исходный массив:", og_array)

Исходный массив: [10 20 30 40 50 60 70 80]


In [11]:
#Получаем отдельный элемент массива
First_element = og_array[0] # Получаем первый элемент с индексои 0
Fivth_element = og_array[4] # Получаем пятый элемент с индексом 4
Eight_element = og_array[7] # Получаем восьмой элемент с индексом 8
Last_element = og_array[-1] # Получаем последний элемент с помощью отрицательной индексации

print("Первый элемент:", First_element)
print("Пятый элемент:", Fivth_element)
print("Восьмой элемент", Eight_element)
print("Последний элемент", Last_element)

Первый элемент: 10
Пятый элемент: 50
Восьмой элемент 80
Последний элемент 80


In [ ]:
#Извлекаем подмассив с помощью среза
slice_1 = og_array[1:5] # Элементы с индексами 1, 2, 3, 4
slice_2 = og_array[1::2] # Каждый второй элемент
slice_3 = og_array [2:] # Все элементы с индекса 2 и до последнего
slice_4 = og_array[:5] # Все элементы до индекса 5, и не включая его

print("Срез [1:5]:", slice_1)
print("Срез [1::2]:", slice_2)
print("Срез [2:]", slice_3)
print("Срез [:5]", slice_4)

Срез [1:5]: [20 30 40 50]
Срез [::2]: [20 40 60 80]
Срез [2:] [30 40 50 60 70 80]
Срез [:5] [10 20 30 40 50]


5. Примеры векторных операций и базовых статистик:

In [ ]:
#Создаем массивы для операций
a = np.array([1, 2, 3, 4, 5, 6])
b = np.array([10, 20, 30, 40, 50, 60])

print("Массив a:", a)
print("Массив b:", b)

Массив a: [1 2 3 4 5 6]
Массив b: [10 20 30 40 50 60]


In [ ]:
#Поэлементарное сложение массивов
add = a+b
print("Поэлементарное сложение массивов:", add )

Поэлементарное сложение массивов [11 22 33 44 55 66]


In [22]:
#Поэлементарное перемножение массивов
multipl = a*b
print("Поэлементное умножение массивов:", multipl)

Поэлементное умножение массивов: [ 10  40  90 160 250 360]


In [24]:
#Поэлементное возвездение в квадрат
sqrt = a**2
sqrt_1 = b**2
print("Возведение элементов массива a в квадрат:", sqrt)
print("Возведение элементов массива b в квадрат:", sqrt_1)

Возведение элементов массива a в квадрат: [ 1  4  9 16 25 36]
Возведение элементов массива b в квадрат: [ 100  400  900 1600 2500 3600]


In [ ]:
#Примеры базовых статистческих операций для массива a
print("Среднее значение:", np.mean(a)) # Определяем среднее значение элементов массива
print("Сумма всех элементов:", np.sum(a)) # Суммируем все элементы массива
print("Максимальное значение:", np.max(a)) # Определяем максимальное значение элемента массива
print("Минимальное значение:", np.min(a))  # Определяем минимальное значение среди элементов массива
print("Стандартное отклонение:", np.std(a)) # Определяем стандартное отклонение элементов массива
print("Медиана:", np.median(a)) # Определяем медиану массива

Среднее значение: 3.5
Сумма всех элементов: 21
Максимальное значение: 6
Минимальное значение: 1
Стандартное отклонение: 1.707825127659933
Медиана: 3.5
